name: 'elevato'
version: '1.0.0'
config-version: 2
profile: 'elevato'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  elevato:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
